version: '3.8'
services:
  db:
    container_name: ${DB_CONTAINER}
    ports:
      - ${DB_PORT}:5432
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations/20231117120136_Initial_setup.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - dev
  # backend:
  #   ports:
  #     - ${BACKEND_PORT}:${BACKEND_PORT}
  #   build: .
  #   environment:
  #     PORT: ${BACKEND_PORT}
  #     DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_CONTAINER}:5432/${DB_NAME}"
  #   depends_on:
  #     - db
  #
  #   networks:
  #     - dev

networks:
  dev:
    driver: bridge
volumes:
  postgres_data:
